services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: crispy
      POSTGRES_PASSWORD: crispy
      POSTGRES_DB: crispy
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U crispy -d crispy']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
