/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AccessToken {
  /**
   * 应用名称
   */
  app_name: Generated<string>;
  /**
   * 渠道
   */
  channel: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 启用状态 10 启用 -10 未启用
   */
  status: Generated<number>;
  /**
   * Token
   */
  token: string;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 用户id
   */
  user_id: Generated<number>;
}

export interface Additions {
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * json对象字符串
   */
  fields_json: string;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 主表id
   */
  primary_id: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
}

export interface AdItems {
  /**
   * 广告位id
   */
  ad_id: Generated<number>;
  /**
   * 内容
   */
  content: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 图片列表
   */
  image_url: Generated<string>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 打开方式
   */
  method: Generated<string>;
  /**
   * 排序
   */
  sort: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 标题
   */
  title: Generated<string>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 链接
   */
  url: Generated<string>;
}

export interface Ads {
  /**
   * 别名
   */
  alias: Generated<string>;
  /**
   * 内容
   */
  content: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 结束时间
   */
  end_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 排序
   */
  sort: Generated<number>;
  /**
   * 开始时间
   */
  start_time: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 标题
   */
  title: Generated<string>;
  /**
   * 类型id
   */
  type_id: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
}

export interface ApiLogs {
  /**
   * post请求
   */
  body: string;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 来源ip
   */
  ip: Generated<string>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 打开方式
   */
  method: Generated<string>;
  /**
   * query请求
   */
  query: string;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 用户id
   */
  user_id: Generated<number>;
}

export interface Articles {
  /**
   * 摘要
   */
  abstract: Generated<string>;
  /**
   * 特殊标签属性
   */
  attrs: Generated<string>;
  /**
   * 作者id
   */
  author_id: Generated<number>;
  /**
   * 点击量
   */
  click: Generated<number>;
  /**
   * 文章内容
   */
  content: string;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 缩略图
   */
  image: Generated<string>;
  /**
   * 文章配图
   */
  image_list: Generated<string>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 是否是markdown 内容
   */
  is_markdown: Generated<number>;
  /**
   * 是否需要审核 1需要 0不需要
   */
  is_review: Generated<number>;
  /**
   * markdown 内容
   */
  markdown_content: Generated<string>;
  /**
   * 跳转链接
   */
  redirect_url: Generated<string>;
  /**
   * 备注
   */
  remark: Generated<string>;
  /**
   * 描述
   */
  seo_description: Generated<string>;
  /**
   * 关键词
   */
  seo_keywords: Generated<string>;
  /**
   * seo标题
   */
  seo_title: Generated<string>;
  /**
   * 排序
   */
  sort: Generated<number>;
  /**
   * 10已发布 -10待发布 -100已删除 -20草稿箱
   */
  status: Generated<number>;
  /**
   * 短标题
   */
  sub_title: Generated<string>;
  /**
   * 标签
   */
  tags: Generated<string>;
  /**
   * 标题
   */
  title: Generated<string>;
  /**
   * 栏目id
   */
  type_id: Generated<number>;
  /**
   * 栏目id
   */
  type_ids: Generated<string>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 路由美化
   */
  url: Generated<string>;
  /**
   * 操作用户id
   */
  user_id: Generated<number>;
}

export interface Attrs {
  /**
   * 别名
   */
  alias: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 排序
   */
  sort: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 标题
   */
  title: Generated<string>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
}

export interface Binary {
  /**
   * 二进制字符串
   */
  binary_str: string;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 键名
   */
  key: Generated<string>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
}

export interface Caches {
  /**
   * 缓存数据
   */
  cache_data: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * hash
   */
  hash: Generated<string>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 原始url
   */
  url: Generated<string>;
}

export interface Categories {
  /**
   * 别名
   */
  alias: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 备注描述
   */
  des: string;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 父级id
   */
  parent_id: Generated<number>;
  /**
   * 排序
   */
  sort: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 标题
   */
  title: Generated<string>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
}

export interface Comments {
  /**
   * 差评
   */
  bad_article: Generated<number>;
  /**
   * 评论内容
   */
  content: string;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 好评
   */
  good_article: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 中立
   */
  not_article: Generated<number>;
  /**
   * 上级评论
   */
  parent_id: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 评论标题
   */
  title: Generated<string>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 评论者Id
   */
  user_id: Generated<number>;
}

export interface Configs {
  /**
   * 别名
   */
  alias: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 排序
   */
  sort: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 标题
   */
  title: Generated<string>;
  /**
   * 设置分类
   */
  type_id: Generated<number>;
  /**
   * 类型ids
   */
  type_ids: Generated<string>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 值
   */
  value: Generated<string>;
}

export interface Enums {
  /**
   * 别名
   */
  alias: Generated<string>;
  /**
   * code
   */
  code: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 排序
   */
  sort: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 标题
   */
  title: Generated<string>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 值
   */
  value: Generated<string>;
}

export interface Holidays {
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 排序
   */
  sort: Generated<number>;
  /**
   * 标题
   */
  title: string;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 值
   */
  value: string;
}

export interface Jobs {
  /**
   * 工作地址
   */
  address: Generated<string>;
  /**
   * 所在部门
   */
  branch: Generated<string>;
  /**
   * 招聘信息
   */
  content: string;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 简历发送邮箱
   */
  email: Generated<string>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 工作性质
   */
  nature: Generated<string>;
  /**
   * 招聘人数
   */
  num: number;
  /**
   * 排序
   */
  sort: Generated<number>;
  /**
   * 职位名称
   */
  title: Generated<string>;
  /**
   * 职位类别
   */
  typeName: Generated<string>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
}

export interface Keywords {
  /**
   * 别名
   */
  alias: Generated<string>;
  /**
   * 点击数
   */
  count: Generated<number>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 标题
   */
  title: Generated<string>;
  /**
   * 分类id
   */
  type_id: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 链接
   */
  url: Generated<string>;
  /**
   * 值
   */
  value: Generated<string>;
}

export interface Links {
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 描述
   */
  des: Generated<string>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * logo
   */
  logo: Generated<string>;
  /**
   * 打开方式
   */
  method: Generated<string>;
  /**
   * 站点名称
   */
  site_name: Generated<string>;
  /**
   * 排序
   */
  sort: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 分类id
   */
  type_id: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 链接
   */
  url: Generated<string>;
}

export interface Menus {
  /**
   * 别名
   */
  alias: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 图标
   */
  icon: Generated<string>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 图片列表
   */
  image_url: Generated<string>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 打开方式
   */
  method: Generated<string>;
  /**
   * 父级id
   */
  parent_id: Generated<number>;
  /**
   * 排序
   */
  sort: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 标题
   */
  title: Generated<string>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 链接
   */
  url: Generated<string>;
}

export interface Notices {
  /**
   * 内容
   */
  content: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 发布者id
   */
  from_user_id: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 发布时间
   */
  publish_time: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 标题
   */
  title: Generated<string>;
  /**
   * 接收者id列表
   */
  tolds: Generated<string>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
}

export interface OperateLogs {
  /**
   * 操作code
   */
  code: Generated<string>;
  /**
   * 操作内容
   */
  content: string;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 分类id
   */
  type_id: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 用户id
   */
  user_id: Generated<number>;
}

export interface Pages {
  /**
   * 摘要
   */
  abstract: Generated<string>;
  /**
   * 别名
   */
  alias: Generated<string>;
  /**
   * 作者id
   */
  author_id: Generated<number>;
  /**
   * 点击量
   */
  click: Generated<number>;
  /**
   * 页面内容
   */
  content: string;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 页面轮播配图
   */
  image_list: Generated<string>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 是否是markdown 内容
   */
  is_markdown: Generated<number>;
  /**
   * markdown 内容
   */
  markdown_content: Generated<string>;
  /**
   * 备注
   */
  remark: Generated<string>;
  /**
   * 描述
   */
  seo_description: Generated<string>;
  /**
   * 关键词
   */
  seo_keywords: Generated<string>;
  /**
   * seo标题
   */
  seo_title: Generated<string>;
  /**
   * 10已发布 -10待发布 -100已删除 -20草稿箱
   */
  status: Generated<number>;
  /**
   * 短标题
   */
  sub_title: Generated<string>;
  /**
   * 标签
   */
  tags: Generated<string>;
  /**
   * 标题
   */
  title: Generated<string>;
  /**
   * 栏目id
   */
  type_id: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 路由美化
   */
  url: Generated<string>;
  /**
   * 操作用户id
   */
  user_id: Generated<number>;
}

export interface Roles {
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 描述
   */
  des: Generated<string>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 所属模块
   */
  module_id: Generated<number>;
  /**
   * 规则列表
   */
  rule_ids: string;
  /**
   * 排序
   */
  sort: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 描述
   */
  title: Generated<string>;
  /**
   * 类型id
   */
  type_id: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
}

export interface Rules {
  /**
   * 别名
   */
  alias: Generated<string>;
  /**
   * 规则
   */
  condition: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 规则描述
   */
  des: Generated<string>;
  /**
   * 图标
   */
  icon: Generated<string>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 模块Id
   */
  module_id: Generated<number>;
  /**
   * 父级id
   */
  parent_id: Generated<number>;
  /**
   * 排序
   */
  sort: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 规则名称
   */
  title: Generated<string>;
  /**
   * 分类id
   */
  type_id: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
}

export interface Tags {
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 描述
   */
  des: Generated<string>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 排序
   */
  sort: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 标题
   */
  title: Generated<string>;
  /**
   * 所属分类
   */
  type_id: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 值
   */
  value: Generated<string>;
}

export interface Todos {
  /**
   * 是否完成
   */
  complete: number;
  /**
   * 内容
   */
  content: string;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 结束时间
   */
  end_time: Generated<number>;
  /**
   * 发布者id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 发布者id
   */
  publish_id: Generated<number>;
  /**
   * 备注
   */
  remark: Generated<string>;
  /**
   * 开始时间
   */
  start_time: Generated<number>;
  /**
   * 状态
   */
  status: number;
  /**
   * 标题
   */
  title: string;
  /**
   * 分类
   */
  type_id: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 用户ids
   */
  user_ids: string;
}

export interface Users {
  /**
   * 头像
   */
  avatar_url: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 邮箱
   */
  email: Generated<string>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否管理员 1是 0否
   */
  is_admin: Generated<number>;
  /**
   * 是否黑名单 1是 0否
   */
  is_black: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 是否系统管理员 1是 0否
   */
  is_super_admin: Generated<number>;
  /**
   * 登录ip
   */
  last_login_ip: Generated<string>;
  /**
   * 登录时间
   */
  last_login_time: Generated<number>;
  /**
   * 昵称
   */
  nick_name: Generated<string>;
  /**
   * 密码
   */
  password: Generated<string>;
  /**
   * 手机号
   */
  phone: Generated<string>;
  /**
   * 用户名
   */
  real_name: Generated<string>;
  /**
   * 角色Id
   */
  role_id: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 分类id
   */
  type_id: Generated<number>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 用户名
   */
  user_name: Generated<string>;
}

export interface UserTypes {
  /**
   * 别名
   */
  alias: Generated<string>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 说明
   */
  remark: Generated<string>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 用户类型名称
   */
  type_name: Generated<string>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
}

export interface VoteItems {
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 标题
   */
  title: Generated<string>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 所属投票id
   */
  vote_id: Generated<number>;
}

export interface Votes {
  /**
   * 投票总数
   */
  count: Generated<number>;
  /**
   * 创建时间
   */
  create_time: Generated<number>;
  /**
   * 结束时间
   */
  end_time: Generated<number>;
  /**
   * 自增id
   */
  id: Generated<number>;
  /**
   * 是否删除
   */
  is_delete: Generated<number>;
  /**
   * 是否多选 1多选 0单选
   */
  is_multiple: Generated<number>;
  /**
   * 开始时间
   */
  start_time: Generated<number>;
  /**
   * 状态
   */
  status: Generated<number>;
  /**
   * 标题
   */
  title: Generated<string>;
  /**
   * 更新时间
   */
  update_time: Generated<number>;
  /**
   * 投票项列表
   */
  vote_items: Generated<string>;
}

export interface DB {
  access_token: AccessToken;
  ad_items: AdItems;
  additions: Additions;
  ads: Ads;
  api_logs: ApiLogs;
  articles: Articles;
  attrs: Attrs;
  binary: Binary;
  caches: Caches;
  categories: Categories;
  comments: Comments;
  configs: Configs;
  enums: Enums;
  holidays: Holidays;
  jobs: Jobs;
  keywords: Keywords;
  links: Links;
  menus: Menus;
  notices: Notices;
  operate_logs: OperateLogs;
  pages: Pages;
  roles: Roles;
  rules: Rules;
  tags: Tags;
  todos: Todos;
  user_types: UserTypes;
  users: Users;
  vote_items: VoteItems;
  votes: Votes;
}
