
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `permissions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model permissions
 * 
 */
export type permissionsModel = runtime.Types.Result.DefaultSelection<Prisma.$permissionsPayload>

export type AggregatePermissions = {
  _count: PermissionsCountAggregateOutputType | null
  _min: PermissionsMinAggregateOutputType | null
  _max: PermissionsMaxAggregateOutputType | null
}

export type PermissionsMinAggregateOutputType = {
  id: string | null
  code: string | null
  name: string | null
  description: string | null
  type: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type PermissionsMaxAggregateOutputType = {
  id: string | null
  code: string | null
  name: string | null
  description: string | null
  type: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type PermissionsCountAggregateOutputType = {
  id: number
  code: number
  name: number
  description: number
  type: number
  status: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type PermissionsMinAggregateInputType = {
  id?: true
  code?: true
  name?: true
  description?: true
  type?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type PermissionsMaxAggregateInputType = {
  id?: true
  code?: true
  name?: true
  description?: true
  type?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type PermissionsCountAggregateInputType = {
  id?: true
  code?: true
  name?: true
  description?: true
  type?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type PermissionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which permissions to aggregate.
   */
  where?: Prisma.permissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of permissions to fetch.
   */
  orderBy?: Prisma.permissionsOrderByWithRelationInput | Prisma.permissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.permissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` permissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` permissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned permissions
  **/
  _count?: true | PermissionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PermissionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PermissionsMaxAggregateInputType
}

export type GetPermissionsAggregateType<T extends PermissionsAggregateArgs> = {
      [P in keyof T & keyof AggregatePermissions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePermissions[P]>
    : Prisma.GetScalarType<T[P], AggregatePermissions[P]>
}




export type permissionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.permissionsWhereInput
  orderBy?: Prisma.permissionsOrderByWithAggregationInput | Prisma.permissionsOrderByWithAggregationInput[]
  by: Prisma.PermissionsScalarFieldEnum[] | Prisma.PermissionsScalarFieldEnum
  having?: Prisma.permissionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PermissionsCountAggregateInputType | true
  _min?: PermissionsMinAggregateInputType
  _max?: PermissionsMaxAggregateInputType
}

export type PermissionsGroupByOutputType = {
  id: string
  code: string
  name: string
  description: string | null
  type: string
  status: string
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: PermissionsCountAggregateOutputType | null
  _min: PermissionsMinAggregateOutputType | null
  _max: PermissionsMaxAggregateOutputType | null
}

type GetPermissionsGroupByPayload<T extends permissionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PermissionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PermissionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PermissionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PermissionsGroupByOutputType[P]>
      }
    >
  > 



export type permissionsWhereInput = {
  AND?: Prisma.permissionsWhereInput | Prisma.permissionsWhereInput[]
  OR?: Prisma.permissionsWhereInput[]
  NOT?: Prisma.permissionsWhereInput | Prisma.permissionsWhereInput[]
  id?: Prisma.StringFilter<"permissions"> | string
  code?: Prisma.StringFilter<"permissions"> | string
  name?: Prisma.StringFilter<"permissions"> | string
  description?: Prisma.StringNullableFilter<"permissions"> | string | null
  type?: Prisma.StringFilter<"permissions"> | string
  status?: Prisma.StringFilter<"permissions"> | string
  createdAt?: Prisma.DateTimeFilter<"permissions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"permissions"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"permissions"> | Date | string | null
  roles?: Prisma.RolesListRelationFilter
}

export type permissionsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  roles?: Prisma.rolesOrderByRelationAggregateInput
}

export type permissionsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  code?: string
  AND?: Prisma.permissionsWhereInput | Prisma.permissionsWhereInput[]
  OR?: Prisma.permissionsWhereInput[]
  NOT?: Prisma.permissionsWhereInput | Prisma.permissionsWhereInput[]
  name?: Prisma.StringFilter<"permissions"> | string
  description?: Prisma.StringNullableFilter<"permissions"> | string | null
  type?: Prisma.StringFilter<"permissions"> | string
  status?: Prisma.StringFilter<"permissions"> | string
  createdAt?: Prisma.DateTimeFilter<"permissions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"permissions"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"permissions"> | Date | string | null
  roles?: Prisma.RolesListRelationFilter
}, "id" | "code">

export type permissionsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.permissionsCountOrderByAggregateInput
  _max?: Prisma.permissionsMaxOrderByAggregateInput
  _min?: Prisma.permissionsMinOrderByAggregateInput
}

export type permissionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.permissionsScalarWhereWithAggregatesInput | Prisma.permissionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.permissionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.permissionsScalarWhereWithAggregatesInput | Prisma.permissionsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"permissions"> | string
  code?: Prisma.StringWithAggregatesFilter<"permissions"> | string
  name?: Prisma.StringWithAggregatesFilter<"permissions"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"permissions"> | string | null
  type?: Prisma.StringWithAggregatesFilter<"permissions"> | string
  status?: Prisma.StringWithAggregatesFilter<"permissions"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"permissions"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"permissions"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"permissions"> | Date | string | null
}

export type permissionsCreateInput = {
  id: string
  code: string
  name: string
  description?: string | null
  type: string
  status?: string
  createdAt?: Date | string
  updatedAt: Date | string
  deletedAt?: Date | string | null
  roles?: Prisma.rolesCreateNestedManyWithoutPermissionsInput
}

export type permissionsUncheckedCreateInput = {
  id: string
  code: string
  name: string
  description?: string | null
  type: string
  status?: string
  createdAt?: Date | string
  updatedAt: Date | string
  deletedAt?: Date | string | null
  roles?: Prisma.rolesUncheckedCreateNestedManyWithoutPermissionsInput
}

export type permissionsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  roles?: Prisma.rolesUpdateManyWithoutPermissionsNestedInput
}

export type permissionsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  roles?: Prisma.rolesUncheckedUpdateManyWithoutPermissionsNestedInput
}

export type permissionsCreateManyInput = {
  id: string
  code: string
  name: string
  description?: string | null
  type: string
  status?: string
  createdAt?: Date | string
  updatedAt: Date | string
  deletedAt?: Date | string | null
}

export type permissionsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type permissionsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type permissionsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type permissionsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type permissionsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type PermissionsListRelationFilter = {
  every?: Prisma.permissionsWhereInput
  some?: Prisma.permissionsWhereInput
  none?: Prisma.permissionsWhereInput
}

export type permissionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type permissionsCreateNestedManyWithoutRolesInput = {
  create?: Prisma.XOR<Prisma.permissionsCreateWithoutRolesInput, Prisma.permissionsUncheckedCreateWithoutRolesInput> | Prisma.permissionsCreateWithoutRolesInput[] | Prisma.permissionsUncheckedCreateWithoutRolesInput[]
  connectOrCreate?: Prisma.permissionsCreateOrConnectWithoutRolesInput | Prisma.permissionsCreateOrConnectWithoutRolesInput[]
  connect?: Prisma.permissionsWhereUniqueInput | Prisma.permissionsWhereUniqueInput[]
}

export type permissionsUncheckedCreateNestedManyWithoutRolesInput = {
  create?: Prisma.XOR<Prisma.permissionsCreateWithoutRolesInput, Prisma.permissionsUncheckedCreateWithoutRolesInput> | Prisma.permissionsCreateWithoutRolesInput[] | Prisma.permissionsUncheckedCreateWithoutRolesInput[]
  connectOrCreate?: Prisma.permissionsCreateOrConnectWithoutRolesInput | Prisma.permissionsCreateOrConnectWithoutRolesInput[]
  connect?: Prisma.permissionsWhereUniqueInput | Prisma.permissionsWhereUniqueInput[]
}

export type permissionsUpdateManyWithoutRolesNestedInput = {
  create?: Prisma.XOR<Prisma.permissionsCreateWithoutRolesInput, Prisma.permissionsUncheckedCreateWithoutRolesInput> | Prisma.permissionsCreateWithoutRolesInput[] | Prisma.permissionsUncheckedCreateWithoutRolesInput[]
  connectOrCreate?: Prisma.permissionsCreateOrConnectWithoutRolesInput | Prisma.permissionsCreateOrConnectWithoutRolesInput[]
  upsert?: Prisma.permissionsUpsertWithWhereUniqueWithoutRolesInput | Prisma.permissionsUpsertWithWhereUniqueWithoutRolesInput[]
  set?: Prisma.permissionsWhereUniqueInput | Prisma.permissionsWhereUniqueInput[]
  disconnect?: Prisma.permissionsWhereUniqueInput | Prisma.permissionsWhereUniqueInput[]
  delete?: Prisma.permissionsWhereUniqueInput | Prisma.permissionsWhereUniqueInput[]
  connect?: Prisma.permissionsWhereUniqueInput | Prisma.permissionsWhereUniqueInput[]
  update?: Prisma.permissionsUpdateWithWhereUniqueWithoutRolesInput | Prisma.permissionsUpdateWithWhereUniqueWithoutRolesInput[]
  updateMany?: Prisma.permissionsUpdateManyWithWhereWithoutRolesInput | Prisma.permissionsUpdateManyWithWhereWithoutRolesInput[]
  deleteMany?: Prisma.permissionsScalarWhereInput | Prisma.permissionsScalarWhereInput[]
}

export type permissionsUncheckedUpdateManyWithoutRolesNestedInput = {
  create?: Prisma.XOR<Prisma.permissionsCreateWithoutRolesInput, Prisma.permissionsUncheckedCreateWithoutRolesInput> | Prisma.permissionsCreateWithoutRolesInput[] | Prisma.permissionsUncheckedCreateWithoutRolesInput[]
  connectOrCreate?: Prisma.permissionsCreateOrConnectWithoutRolesInput | Prisma.permissionsCreateOrConnectWithoutRolesInput[]
  upsert?: Prisma.permissionsUpsertWithWhereUniqueWithoutRolesInput | Prisma.permissionsUpsertWithWhereUniqueWithoutRolesInput[]
  set?: Prisma.permissionsWhereUniqueInput | Prisma.permissionsWhereUniqueInput[]
  disconnect?: Prisma.permissionsWhereUniqueInput | Prisma.permissionsWhereUniqueInput[]
  delete?: Prisma.permissionsWhereUniqueInput | Prisma.permissionsWhereUniqueInput[]
  connect?: Prisma.permissionsWhereUniqueInput | Prisma.permissionsWhereUniqueInput[]
  update?: Prisma.permissionsUpdateWithWhereUniqueWithoutRolesInput | Prisma.permissionsUpdateWithWhereUniqueWithoutRolesInput[]
  updateMany?: Prisma.permissionsUpdateManyWithWhereWithoutRolesInput | Prisma.permissionsUpdateManyWithWhereWithoutRolesInput[]
  deleteMany?: Prisma.permissionsScalarWhereInput | Prisma.permissionsScalarWhereInput[]
}

export type permissionsCreateWithoutRolesInput = {
  id: string
  code: string
  name: string
  description?: string | null
  type: string
  status?: string
  createdAt?: Date | string
  updatedAt: Date | string
  deletedAt?: Date | string | null
}

export type permissionsUncheckedCreateWithoutRolesInput = {
  id: string
  code: string
  name: string
  description?: string | null
  type: string
  status?: string
  createdAt?: Date | string
  updatedAt: Date | string
  deletedAt?: Date | string | null
}

export type permissionsCreateOrConnectWithoutRolesInput = {
  where: Prisma.permissionsWhereUniqueInput
  create: Prisma.XOR<Prisma.permissionsCreateWithoutRolesInput, Prisma.permissionsUncheckedCreateWithoutRolesInput>
}

export type permissionsUpsertWithWhereUniqueWithoutRolesInput = {
  where: Prisma.permissionsWhereUniqueInput
  update: Prisma.XOR<Prisma.permissionsUpdateWithoutRolesInput, Prisma.permissionsUncheckedUpdateWithoutRolesInput>
  create: Prisma.XOR<Prisma.permissionsCreateWithoutRolesInput, Prisma.permissionsUncheckedCreateWithoutRolesInput>
}

export type permissionsUpdateWithWhereUniqueWithoutRolesInput = {
  where: Prisma.permissionsWhereUniqueInput
  data: Prisma.XOR<Prisma.permissionsUpdateWithoutRolesInput, Prisma.permissionsUncheckedUpdateWithoutRolesInput>
}

export type permissionsUpdateManyWithWhereWithoutRolesInput = {
  where: Prisma.permissionsScalarWhereInput
  data: Prisma.XOR<Prisma.permissionsUpdateManyMutationInput, Prisma.permissionsUncheckedUpdateManyWithoutRolesInput>
}

export type permissionsScalarWhereInput = {
  AND?: Prisma.permissionsScalarWhereInput | Prisma.permissionsScalarWhereInput[]
  OR?: Prisma.permissionsScalarWhereInput[]
  NOT?: Prisma.permissionsScalarWhereInput | Prisma.permissionsScalarWhereInput[]
  id?: Prisma.StringFilter<"permissions"> | string
  code?: Prisma.StringFilter<"permissions"> | string
  name?: Prisma.StringFilter<"permissions"> | string
  description?: Prisma.StringNullableFilter<"permissions"> | string | null
  type?: Prisma.StringFilter<"permissions"> | string
  status?: Prisma.StringFilter<"permissions"> | string
  createdAt?: Prisma.DateTimeFilter<"permissions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"permissions"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"permissions"> | Date | string | null
}

export type permissionsUpdateWithoutRolesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type permissionsUncheckedUpdateWithoutRolesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type permissionsUncheckedUpdateManyWithoutRolesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type PermissionsCountOutputType
 */

export type PermissionsCountOutputType = {
  roles: number
}

export type PermissionsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  roles?: boolean | PermissionsCountOutputTypeCountRolesArgs
}

/**
 * PermissionsCountOutputType without action
 */
export type PermissionsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermissionsCountOutputType
   */
  select?: Prisma.PermissionsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PermissionsCountOutputType without action
 */
export type PermissionsCountOutputTypeCountRolesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.rolesWhereInput
}


export type permissionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  description?: boolean
  type?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  roles?: boolean | Prisma.permissions$rolesArgs<ExtArgs>
  _count?: boolean | Prisma.PermissionsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["permissions"]>

export type permissionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  description?: boolean
  type?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["permissions"]>

export type permissionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  description?: boolean
  type?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["permissions"]>

export type permissionsSelectScalar = {
  id?: boolean
  code?: boolean
  name?: boolean
  description?: boolean
  type?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type permissionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "code" | "name" | "description" | "type" | "status" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["permissions"]>
export type permissionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  roles?: boolean | Prisma.permissions$rolesArgs<ExtArgs>
  _count?: boolean | Prisma.PermissionsCountOutputTypeDefaultArgs<ExtArgs>
}
export type permissionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type permissionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $permissionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "permissions"
  objects: {
    roles: Prisma.$rolesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    code: string
    name: string
    description: string | null
    type: string
    status: string
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["permissions"]>
  composites: {}
}

export type permissionsGetPayload<S extends boolean | null | undefined | permissionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$permissionsPayload, S>

export type permissionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<permissionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PermissionsCountAggregateInputType | true
  }

export interface permissionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['permissions'], meta: { name: 'permissions' } }
  /**
   * Find zero or one Permissions that matches the filter.
   * @param {permissionsFindUniqueArgs} args - Arguments to find a Permissions
   * @example
   * // Get one Permissions
   * const permissions = await prisma.permissions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends permissionsFindUniqueArgs>(args: Prisma.SelectSubset<T, permissionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__permissionsClient<runtime.Types.Result.GetResult<Prisma.$permissionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Permissions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {permissionsFindUniqueOrThrowArgs} args - Arguments to find a Permissions
   * @example
   * // Get one Permissions
   * const permissions = await prisma.permissions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends permissionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, permissionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__permissionsClient<runtime.Types.Result.GetResult<Prisma.$permissionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Permissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {permissionsFindFirstArgs} args - Arguments to find a Permissions
   * @example
   * // Get one Permissions
   * const permissions = await prisma.permissions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends permissionsFindFirstArgs>(args?: Prisma.SelectSubset<T, permissionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__permissionsClient<runtime.Types.Result.GetResult<Prisma.$permissionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Permissions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {permissionsFindFirstOrThrowArgs} args - Arguments to find a Permissions
   * @example
   * // Get one Permissions
   * const permissions = await prisma.permissions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends permissionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, permissionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__permissionsClient<runtime.Types.Result.GetResult<Prisma.$permissionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Permissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {permissionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Permissions
   * const permissions = await prisma.permissions.findMany()
   * 
   * // Get first 10 Permissions
   * const permissions = await prisma.permissions.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const permissionsWithIdOnly = await prisma.permissions.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends permissionsFindManyArgs>(args?: Prisma.SelectSubset<T, permissionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$permissionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Permissions.
   * @param {permissionsCreateArgs} args - Arguments to create a Permissions.
   * @example
   * // Create one Permissions
   * const Permissions = await prisma.permissions.create({
   *   data: {
   *     // ... data to create a Permissions
   *   }
   * })
   * 
   */
  create<T extends permissionsCreateArgs>(args: Prisma.SelectSubset<T, permissionsCreateArgs<ExtArgs>>): Prisma.Prisma__permissionsClient<runtime.Types.Result.GetResult<Prisma.$permissionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Permissions.
   * @param {permissionsCreateManyArgs} args - Arguments to create many Permissions.
   * @example
   * // Create many Permissions
   * const permissions = await prisma.permissions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends permissionsCreateManyArgs>(args?: Prisma.SelectSubset<T, permissionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Permissions and returns the data saved in the database.
   * @param {permissionsCreateManyAndReturnArgs} args - Arguments to create many Permissions.
   * @example
   * // Create many Permissions
   * const permissions = await prisma.permissions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Permissions and only return the `id`
   * const permissionsWithIdOnly = await prisma.permissions.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends permissionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, permissionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$permissionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Permissions.
   * @param {permissionsDeleteArgs} args - Arguments to delete one Permissions.
   * @example
   * // Delete one Permissions
   * const Permissions = await prisma.permissions.delete({
   *   where: {
   *     // ... filter to delete one Permissions
   *   }
   * })
   * 
   */
  delete<T extends permissionsDeleteArgs>(args: Prisma.SelectSubset<T, permissionsDeleteArgs<ExtArgs>>): Prisma.Prisma__permissionsClient<runtime.Types.Result.GetResult<Prisma.$permissionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Permissions.
   * @param {permissionsUpdateArgs} args - Arguments to update one Permissions.
   * @example
   * // Update one Permissions
   * const permissions = await prisma.permissions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends permissionsUpdateArgs>(args: Prisma.SelectSubset<T, permissionsUpdateArgs<ExtArgs>>): Prisma.Prisma__permissionsClient<runtime.Types.Result.GetResult<Prisma.$permissionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Permissions.
   * @param {permissionsDeleteManyArgs} args - Arguments to filter Permissions to delete.
   * @example
   * // Delete a few Permissions
   * const { count } = await prisma.permissions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends permissionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, permissionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Permissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {permissionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Permissions
   * const permissions = await prisma.permissions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends permissionsUpdateManyArgs>(args: Prisma.SelectSubset<T, permissionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Permissions and returns the data updated in the database.
   * @param {permissionsUpdateManyAndReturnArgs} args - Arguments to update many Permissions.
   * @example
   * // Update many Permissions
   * const permissions = await prisma.permissions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Permissions and only return the `id`
   * const permissionsWithIdOnly = await prisma.permissions.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends permissionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, permissionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$permissionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Permissions.
   * @param {permissionsUpsertArgs} args - Arguments to update or create a Permissions.
   * @example
   * // Update or create a Permissions
   * const permissions = await prisma.permissions.upsert({
   *   create: {
   *     // ... data to create a Permissions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Permissions we want to update
   *   }
   * })
   */
  upsert<T extends permissionsUpsertArgs>(args: Prisma.SelectSubset<T, permissionsUpsertArgs<ExtArgs>>): Prisma.Prisma__permissionsClient<runtime.Types.Result.GetResult<Prisma.$permissionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Permissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {permissionsCountArgs} args - Arguments to filter Permissions to count.
   * @example
   * // Count the number of Permissions
   * const count = await prisma.permissions.count({
   *   where: {
   *     // ... the filter for the Permissions we want to count
   *   }
   * })
  **/
  count<T extends permissionsCountArgs>(
    args?: Prisma.Subset<T, permissionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PermissionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Permissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermissionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PermissionsAggregateArgs>(args: Prisma.Subset<T, PermissionsAggregateArgs>): Prisma.PrismaPromise<GetPermissionsAggregateType<T>>

  /**
   * Group by Permissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {permissionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends permissionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: permissionsGroupByArgs['orderBy'] }
      : { orderBy?: permissionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, permissionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPermissionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the permissions model
 */
readonly fields: permissionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for permissions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__permissionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  roles<T extends Prisma.permissions$rolesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.permissions$rolesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$rolesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the permissions model
 */
export interface permissionsFieldRefs {
  readonly id: Prisma.FieldRef<"permissions", 'String'>
  readonly code: Prisma.FieldRef<"permissions", 'String'>
  readonly name: Prisma.FieldRef<"permissions", 'String'>
  readonly description: Prisma.FieldRef<"permissions", 'String'>
  readonly type: Prisma.FieldRef<"permissions", 'String'>
  readonly status: Prisma.FieldRef<"permissions", 'String'>
  readonly createdAt: Prisma.FieldRef<"permissions", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"permissions", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"permissions", 'DateTime'>
}
    

// Custom InputTypes
/**
 * permissions findUnique
 */
export type permissionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the permissions
   */
  select?: Prisma.permissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the permissions
   */
  omit?: Prisma.permissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.permissionsInclude<ExtArgs> | null
  /**
   * Filter, which permissions to fetch.
   */
  where: Prisma.permissionsWhereUniqueInput
}

/**
 * permissions findUniqueOrThrow
 */
export type permissionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the permissions
   */
  select?: Prisma.permissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the permissions
   */
  omit?: Prisma.permissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.permissionsInclude<ExtArgs> | null
  /**
   * Filter, which permissions to fetch.
   */
  where: Prisma.permissionsWhereUniqueInput
}

/**
 * permissions findFirst
 */
export type permissionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the permissions
   */
  select?: Prisma.permissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the permissions
   */
  omit?: Prisma.permissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.permissionsInclude<ExtArgs> | null
  /**
   * Filter, which permissions to fetch.
   */
  where?: Prisma.permissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of permissions to fetch.
   */
  orderBy?: Prisma.permissionsOrderByWithRelationInput | Prisma.permissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for permissions.
   */
  cursor?: Prisma.permissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` permissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` permissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of permissions.
   */
  distinct?: Prisma.PermissionsScalarFieldEnum | Prisma.PermissionsScalarFieldEnum[]
}

/**
 * permissions findFirstOrThrow
 */
export type permissionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the permissions
   */
  select?: Prisma.permissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the permissions
   */
  omit?: Prisma.permissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.permissionsInclude<ExtArgs> | null
  /**
   * Filter, which permissions to fetch.
   */
  where?: Prisma.permissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of permissions to fetch.
   */
  orderBy?: Prisma.permissionsOrderByWithRelationInput | Prisma.permissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for permissions.
   */
  cursor?: Prisma.permissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` permissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` permissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of permissions.
   */
  distinct?: Prisma.PermissionsScalarFieldEnum | Prisma.PermissionsScalarFieldEnum[]
}

/**
 * permissions findMany
 */
export type permissionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the permissions
   */
  select?: Prisma.permissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the permissions
   */
  omit?: Prisma.permissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.permissionsInclude<ExtArgs> | null
  /**
   * Filter, which permissions to fetch.
   */
  where?: Prisma.permissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of permissions to fetch.
   */
  orderBy?: Prisma.permissionsOrderByWithRelationInput | Prisma.permissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing permissions.
   */
  cursor?: Prisma.permissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` permissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` permissions.
   */
  skip?: number
  distinct?: Prisma.PermissionsScalarFieldEnum | Prisma.PermissionsScalarFieldEnum[]
}

/**
 * permissions create
 */
export type permissionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the permissions
   */
  select?: Prisma.permissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the permissions
   */
  omit?: Prisma.permissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.permissionsInclude<ExtArgs> | null
  /**
   * The data needed to create a permissions.
   */
  data: Prisma.XOR<Prisma.permissionsCreateInput, Prisma.permissionsUncheckedCreateInput>
}

/**
 * permissions createMany
 */
export type permissionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many permissions.
   */
  data: Prisma.permissionsCreateManyInput | Prisma.permissionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * permissions createManyAndReturn
 */
export type permissionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the permissions
   */
  select?: Prisma.permissionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the permissions
   */
  omit?: Prisma.permissionsOmit<ExtArgs> | null
  /**
   * The data used to create many permissions.
   */
  data: Prisma.permissionsCreateManyInput | Prisma.permissionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * permissions update
 */
export type permissionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the permissions
   */
  select?: Prisma.permissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the permissions
   */
  omit?: Prisma.permissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.permissionsInclude<ExtArgs> | null
  /**
   * The data needed to update a permissions.
   */
  data: Prisma.XOR<Prisma.permissionsUpdateInput, Prisma.permissionsUncheckedUpdateInput>
  /**
   * Choose, which permissions to update.
   */
  where: Prisma.permissionsWhereUniqueInput
}

/**
 * permissions updateMany
 */
export type permissionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update permissions.
   */
  data: Prisma.XOR<Prisma.permissionsUpdateManyMutationInput, Prisma.permissionsUncheckedUpdateManyInput>
  /**
   * Filter which permissions to update
   */
  where?: Prisma.permissionsWhereInput
  /**
   * Limit how many permissions to update.
   */
  limit?: number
}

/**
 * permissions updateManyAndReturn
 */
export type permissionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the permissions
   */
  select?: Prisma.permissionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the permissions
   */
  omit?: Prisma.permissionsOmit<ExtArgs> | null
  /**
   * The data used to update permissions.
   */
  data: Prisma.XOR<Prisma.permissionsUpdateManyMutationInput, Prisma.permissionsUncheckedUpdateManyInput>
  /**
   * Filter which permissions to update
   */
  where?: Prisma.permissionsWhereInput
  /**
   * Limit how many permissions to update.
   */
  limit?: number
}

/**
 * permissions upsert
 */
export type permissionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the permissions
   */
  select?: Prisma.permissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the permissions
   */
  omit?: Prisma.permissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.permissionsInclude<ExtArgs> | null
  /**
   * The filter to search for the permissions to update in case it exists.
   */
  where: Prisma.permissionsWhereUniqueInput
  /**
   * In case the permissions found by the `where` argument doesn't exist, create a new permissions with this data.
   */
  create: Prisma.XOR<Prisma.permissionsCreateInput, Prisma.permissionsUncheckedCreateInput>
  /**
   * In case the permissions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.permissionsUpdateInput, Prisma.permissionsUncheckedUpdateInput>
}

/**
 * permissions delete
 */
export type permissionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the permissions
   */
  select?: Prisma.permissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the permissions
   */
  omit?: Prisma.permissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.permissionsInclude<ExtArgs> | null
  /**
   * Filter which permissions to delete.
   */
  where: Prisma.permissionsWhereUniqueInput
}

/**
 * permissions deleteMany
 */
export type permissionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which permissions to delete
   */
  where?: Prisma.permissionsWhereInput
  /**
   * Limit how many permissions to delete.
   */
  limit?: number
}

/**
 * permissions.roles
 */
export type permissions$rolesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the roles
   */
  select?: Prisma.rolesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the roles
   */
  omit?: Prisma.rolesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rolesInclude<ExtArgs> | null
  where?: Prisma.rolesWhereInput
  orderBy?: Prisma.rolesOrderByWithRelationInput | Prisma.rolesOrderByWithRelationInput[]
  cursor?: Prisma.rolesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RolesScalarFieldEnum | Prisma.RolesScalarFieldEnum[]
}

/**
 * permissions without action
 */
export type permissionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the permissions
   */
  select?: Prisma.permissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the permissions
   */
  omit?: Prisma.permissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.permissionsInclude<ExtArgs> | null
}
