export const STATUS_PUBLISHED = 10
export const STATUS_DRAFT = -10
export const STATUS_DELETED = -100
export const STATUS_TRASH = -20
export const STATUS_TRUE = 1
export const STATUS_FALSE = 0

export const STATUS_MAP = {
  [STATUS_PUBLISHED]: '已发布',
  [STATUS_DRAFT]: '待发布',
  [STATUS_DELETED]: '已删除',
  [STATUS_TRASH]: '回收站'
}

export const PUBLISH_STATUS = {
  PUBLISHED: STATUS_PUBLISHED,
  DRAFT: STATUS_DRAFT,
  DELETED: STATUS_DELETED,
  TRASH: STATUS_TRASH
} as const

export const DELETE_STATUS = {
  DELETE: STATUS_TRUE,
  UN_DELETE: STATUS_FALSE
} as const

export const USER_STATUS = {
  ENABLE: STATUS_PUBLISHED,
  DISABLE: STATUS_DRAFT
} as const

export const SYSTEM_CATEGORY_ALIAS = '_SYS_CAT'

export const SYSTEM_CATEGORY_ROOT_ID = 0
export const SYSTEM_CATEGORY_GOD_ID = 1
export const SYSTEM_CATEGORY_PARENT_ID_LIST = [SYSTEM_CATEGORY_ROOT_ID, SYSTEM_CATEGORY_GOD_ID]

export const SYSTEM_CATEGORY_LIST = {
  GOD_SYS_CAT: 'GOD_SYS_CAT',
  AD_SYS_CAT: 'AD_SYS_CAT',
  ARTICLE_SYS_CAT: 'ARTICLE_SYS_CAT',
  PAGE_SYS_CAT: 'PAGE_SYS_CAT',
  LINK_SYS_CAT: 'LINK_SYS_CAT',
  COMMENT_SYS_CAT: 'COMMENT_SYS_CAT',
  TAG_SYS_CAT: 'TAG_SYS_CAT',
  SITE_CONFIG_SYS_CAT: 'SITE_CONFIG_SYS_CAT'
} as const
